spring.application.name=candidate-app
server.port=9021

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/sandbox_db}
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate


jwt.secret=IniAdalahTeksRahasiaDanSangatPanjangUntukKeamananBcryptDanJwt2026